### ISSUE TITLE
我是西安交大电气32班的学生，目前在fir.im实习，参与flow.ci这个产品的测试

### ISSUE THREAD

**Issue by KaneHui** [ghouzenyan/XJTU-eleme-blacklist#1]
同学你好，我是西安交大电气32班的学生，我目前fir.im实习，主要参与flow.ci这个产品的测试，我刚才在后台看到了一个XJTU的项目，很好奇是不是咱们学校同学的项目，感觉很巧，想问问你对flow.ci这个产品有什么建议么？非常期待你的建议和留言！

**Comment by ghouzenyan** [comment]
刚刚接触，对 flow.ci 还不太了解，如果非要说的话，能不能像 travis ci 那样，有 `build|passing` 这样的状态？:smile:

**Comment by KaneHui** [comment]
好的，谢谢你的反馈和建议，我们这边会和团队沟通😄，如果你在使用flow.ci的时候有任何问题，欢迎点击flow.ci页面右下角的按钮进行留言，祝你学习生活愉快😄
